repository: chengmengerlai/navi
repository_url: https://github.com/chengmengerlai/navi

timezone: Asia/Shanghai
lang: zh_CN

title: Euarne导航 · Euarne-Navi
alias_en: Euarne-Navi
alias_cn: Euarne导航
description: A Navigation Website for Euarne
keywords: Euarne导航, Euarne-Navi, Euarne, Navi, Navigation
url: https://navi.euarne.com
established_at: "2020-10-01T00:00+08:00"

author: Euarne
author_url: https://me.euarne.com
organization: Euarne GitHub
organization_url: https://github.euarne.com
contact: contact[at]euarne[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
